### ISSUE TITLE
requiresMainQueueSetup omission

### ISSUE THREAD

**Issue by ZackTRobertson** [fixd/react-native-locale#24]
Not sure if I should make this a pull request but I got this warning in the IOS simulator.

`Module RNLocale requires main queue setup since it overrides constantsToExport but doesn't implement requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`

It didn't cause the app build to fail or compromise performance but the issue has to do with the RCTLocale.m library lacking the following declaration at the end:

```
+ (BOOL)requiresMainQueueSetup
{
    return YES;
}
```
It was easy enough to make the adjustment in X-code but it would probably be worth fixing.

React-Native 0.51.0
react-native-locale 0.18

**Comment by ericketts** [comment]
Fairly confused as to how this warning only started showing up for me today given the age of this ticket, but indeed it has, so I'd add a +1.

**Comment by patrickomeara** [comment]
@ericketts Did @ZackTRobertson's solution above work for you?

**Comment by toytonic** [comment]
Same here: RN 0.56

**Comment by patrickomeara** [comment]
@toytonic Did @ZackTRobertson's solution fix the issue?

**Comment by toytonic** [comment]
Yes, it did. Don't know what the implications of this are. Only did a quick google and saw other libs implementing it as well.

**Comment by patrickomeara** [comment]
Thanks @toytonic if someone wants to create a PR I'll merge this in, otherwise we will fix it on our next update.

**Comment by patrickomeara** [comment]
Fixed in 0.0.19 

Thanks @rikur
